### PR TITLE
csr fix

### LINKED ISSUE #49: Use CSR numbers when accessing CSR instead of CSR alias names
We should use CSR numbers everywhere to support older toolchains

### PR DESCRIPTION
**Pull request by atishp04**
Some older toolchain may not have all csr defined.
Update all csr functions to use defined CSR_ values instead of
toolchain defined values.

This fixes #49

### CODE REVIEW

**Comment by alistair23** [comment]
Can you tidy up the commit message? Something like this?
Some older toolchains may not have all csr's defined.
Update all the csr functions to use defined CSR_ values instead of
the toolchain defined values.

**Comment by avpatel** [comment]
Can you please do same changes in firmware/ directory as well?

**Comment by atishp04** [comment]
> Can you tidy up the commit message? Something like this?
> 
> > Some older toolchains may not have all the csr's defined.
> > Update all the csr functions to use the CSR_ #define values instead of
> > the toolchain defined values.

Done. Updated PR.

**Comment by atishp04** [comment]
> Can you please do same changes in firmware/ directory as well?

Done. Updated PR.

**Pull request merged**
