### PR TITLE
Fence revert

### PR DESCRIPTION
**Pull request by atishp04**

### CODE REVIEW

**Comment by wxjstz** [comment]
warm reset issue ???

**Comment by avpatel** [comment]
Yes, some thing out-of-sync when we use "reset button" (warm boot) on SiFive Unleashed board. Although, cold-boot using power-on button works perfectly fine on SiFive Unleashed board.

Refer, https://github.com/riscv/opensbi/issues/65

We have few fixes in-place for warm boot (submitted by Atish) but the "fence rw,rw" patch is again causing warm boot issue to re-appear so for time-being we have reverted it.

**Comment by atishp04** [comment]
No need to merge this. I have raised another PR with fence revert and some additional required warm reset fix.

**Comment by alistair23** [comment]
Closing the PR as requested

**Pull request closed without merging**
