### PR TITLE
use __builtin_ctzl

### PR DESCRIPTION
**Pull request by lijinpei**

### CODE REVIEW

**Comment by avpatel** [comment]
Send your patches to OpenSBI mailing list using "git send-email".

To join OpenSBI mailing list, visit:
http://lists.infradead.org/mailman/listinfo/opensbi

Regards,
Anup

**Comment by avpatel** [comment]
Can you let me know your name and email address so that I can send it to OpenSBI list and merge it ?

Regards,
Anup

**Comment by JohnAZoidberg** [comment]
> Can you let me know your name and email address so that I can send it to OpenSBI list and merge it ?

The commits say: `Li Jinpei <leekingp1994@163.com>`

**Comment by avpatel** [comment]
I have send these patches to OpenSBI mailing list.

**Comment by avpatel** [comment]
These patches are now merged.

**Comment by philhug** [comment]
@avpatel please revert that change as it breaks PLATFORM=qemu/virt

 ELF       platform/qemu/virt/firmware/fw_dynamic.elf
/opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/libgcc.a(_ctzsi2.o): can't link double-float modules with soft-float modules
/opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/libgcc.a(_ctzsi2.o)
/opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/libgcc.a(_clz.o): can't link double-float modules with soft-float modules
/opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/libgcc.a(_clz.o)
/opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/libgcc.a(_ctzsi2.o): in function `__ctzdi2':
/home/googletv/riscv-gnu-toolchain/build-gcc-newlib-stage2/riscv64-unknown-elf/libgcc/../../.././riscv-gcc/libgcc/libgcc2.c:742:(.text+0x18): relocation truncated to fit: R_RISCV_HI20 against symbol `__clz_tab' defined in .rodata section in /opt/riscv/lib/gcc/riscv64-unknown-elf/9.2.0/libgcc.a(_clz.o)
collect2: error: ld returned 1 exit status
Makefile:285: recipe for target '/home/googletv/coreboot/3rdparty/opensbi/build/platform/qemu/virt/firmware/fw_dynamic.elf' failed
make: *** [/home/googletv/coreboot/3rdparty/opensbi/build/platform/qemu/virt/firmware/fw_dynamic.elf] Error 1

**Comment by avpatel** [comment]
Ahh, I see. This fails to compile with newlib toolchain.

I will revert this patch. Thanks for reporting.

Regards,
Anup

**Comment by avpatel** [comment]
I have reverted this commit.

Can you try latest opensbi master branch ?

Regards,
Anup

**Comment by philhug** [comment]
thanks, works fine again.
philipp

**Pull request closed without merging**
