### PR TITLE
libfdt: Upgrade to v1.6.0 release

### PR DESCRIPTION
**Pull request by xnox**
Sync with libfdt v1.6.0 release source codes.

Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

### CODE REVIEW

**Comment by xnox** [comment]
As part of Ubuntu Main Inclusion Requirements inspection, it has been identified that opensbi includes an out of date embedded copy of libfdt. This pull request update to 1.6.0 release.

I have test built generic & fu540 platforms. I don't have access to anything else. Ideally this should be tested on them all.

**Comment by atishp04** [comment]
Thanks for the PR. It is exciting to see that OpenSBI images are available in Ubuntu now. Is there a plan to port Ubuntu to RISC-V ?

About the PR, it looks good to me. It's preferred to review the changes in the mailing list rather than github as more folks watch that. You do need to join OpenSBI mailing list before sending the series. Let us know if you face any issues.

**Comment by xnox** [comment]
> Thanks for the PR. It is exciting to see that OpenSBI images are available in Ubuntu now. Is there a plan to port Ubuntu to RISC-V ?
> 

Ubuntu has been ported to RISC-V, and we do build images that are bootable with QEMU, and on the Unleashed board when booted from SPI.

When booting from MMC only, as should be possible (image has loader1/loader2/rootfs partitions), our u-boot SPL loads and then we hit illegal instructions =(

You can find riscv64 .img.xz at https://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/current/
I.e. hirsute-preinstalled-server-riscv64.img.xz

Instead of https://u-boot.readthedocs.io/en/latest/board/sifive/fu540.html#id4 we are currently getting

```
U-Boot SPL 2020.10+dfsg-1ubuntu4 (Dec 08 2020 - 09:04:00 +0000)
Trying to boot from MMC1
0nhandledUUUnhadndled eeexception: Ilaleinsagalt instructio0n
 0EPC00:0 0000000000800000000L0 007 R0A: 640057000000008000a40 cTVAL: 060O0007000464arec457f
###S EaRRO#R ### Please RESET the board ###
```

> About the PR, it looks good to me. It's preferred to review the changes in the mailing list rather than github as more folks watch that. You do need to join OpenSBI mailing list before sending the series. Let us know if you face any issues.

Setup github PR emails => mailing list? =) I can send stuff there too, that's fine, no worries.

**Comment by atishp04** [comment]
> > Thanks for the PR. It is exciting to see that OpenSBI images are available in Ubuntu now. Is there a plan to port Ubuntu to RISC-V ?
> 
> Ubuntu has been ported to RISC-V, and we do build images that are bootable with QEMU, and on the Unleashed board when booted from SPI.
> 
> When booting from MMC only, as should be possible (image has loader1/loader2/rootfs partitions), our u-boot SPL loads and then we hit illegal instructions =(
> 
> You can find riscv64 .img.xz at https://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/current/
> I.e. hirsute-preinstalled-server-riscv64.img.xz
> 

Awesome. I didn't know they already exist!. Thanks.

> Instead of https://u-boot.readthedocs.io/en/latest/board/sifive/fu540.html#id4 we are currently getting
> 
> ```
> U-Boot SPL 2020.10+dfsg-1ubuntu4 (Dec 08 2020 - 09:04:00 +0000)
> Trying to boot from MMC1
> 0nhandledUUUnhadndled eeexception: Ilaleinsagalt instructio0n
>  0EPC00:0 0000000000800000000L0 007 R0A: 640057000000008000a40 cTVAL: 060O0007000464arec457f
> ###S EaRRO#R ### Please RESET the board ###
> ```
> 

That's odd. The console output seems to be weird as well (two harts writing to the console ?). I would send an email to the U-Boot mailing list.

> > About the PR, it looks good to me. It's preferred to review the changes in the mailing list rather than github as more folks watch that. You do need to join OpenSBI mailing list before sending the series. Let us know if you face any issues.
> 
> Setup github PR emails => mailing list? =) I can send stuff there too, that's fine, no worries.

Is there an easy way to do it ? We tried to explore that in the past. IIRC,  Github allows to send only notification of the PR to the mailing list but doesn't send as a proper patch. I may be wrong about this as it was tried some 1.5 years back.

Some automation script can be written that pulls the PR from github, send it to the mailing list. But the traffic on Github PR is not that high to warrant the effort.

**Comment by xnox** [comment]
> > > Thanks for the PR. It is exciting to see that OpenSBI images are available in Ubuntu now. Is there a plan to port Ubuntu to RISC-V ?
> > 
> > 
> > Ubuntu has been ported to RISC-V, and we do build images that are bootable with QEMU, and on the Unleashed board when booted from SPI.
> > When booting from MMC only, as should be possible (image has loader1/loader2/rootfs partitions), our u-boot SPL loads and then we hit illegal instructions =(
> > You can find riscv64 .img.xz at https://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/current/
> > I.e. hirsute-preinstalled-server-riscv64.img.xz
> 
> Awesome. I didn't know they already exist!. Thanks.
> 
> > Instead of https://u-boot.readthedocs.io/en/latest/board/sifive/fu540.html#id4 we are currently getting
> > ```
> > U-Boot SPL 2020.10+dfsg-1ubuntu4 (Dec 08 2020 - 09:04:00 +0000)
> > Trying to boot from MMC1
> > 0nhandledUUUnhadndled eeexception: Ilaleinsagalt instructio0n
> >  0EPC00:0 0000000000800000000L0 007 R0A: 640057000000008000a40 cTVAL: 060O0007000464arec457f
> > ###S EaRRO#R ### Please RESET the board ###
> > ```
> 
> That's odd. The console output seems to be weird as well (two harts writing to the console ?). I would send an email to the U-Boot mailing list.

we always get two consoles. Not sure why. Like hvc0 + some-other (ie. ttySIFY01 or some odd one for qemu).

> 
> > > About the PR, it looks good to me. It's preferred to review the changes in the mailing list rather than github as more folks watch that. You do need to join OpenSBI mailing list before sending the series. Let us know if you face any issues.
> > 
> > 
> > Setup github PR emails => mailing list? =) I can send stuff there too, that's fine, no worries.
> 
> Is there an easy way to do it ? We tried to explore that in the past. IIRC, Github allows to send only notification of the PR to the mailing list but doesn't send as a proper patch. I may be wrong about this as it was tried some 1.5 years back.
> 
> Some automation script can be written that pulls the PR from github, send it to the mailing list. But the traffic on Github PR is not that high to warrant the effort.

Fair enough. There is https://github.com/google/pull-request-mailer but it's not quite a "enable github action and forget about it" type of thing.

**Comment by atishp04** [comment]
The patch is already merged. Closing the PR.

**Pull request closed without merging**
