### PR TITLE
docs: Add a payload section about coreboot support

### PR DESCRIPTION
**Pull request by citypw**
docs: Add a payload section about coreboot support

### CODE REVIEW

**Comment by avpatel** [comment]
The documentation in docs/firmware/payload_<xyz>.md should contain info about using <xyz> software as payload to OpenSBI.

The documentation in docs/firmware/payload_coreboot.md is not aligned with above. It describes how OpenSBI+Linux combined image can be made payload of Coreboot. This information does not belong in docs/firmware.

I suggest you move this to docs/external/coreboot.md and title in the documentation should be "OpenSBI as Coreboot Payload". Also, please replace "BBL/OpenSBI" with just "OpenSBI". We don't provide BBL documentation in OpenSBI

**Comment by citypw** [comment]
Thanks for pointing out, will do later.

**Comment by citypw** [comment]
Done! Could you plz review it again?

**Comment by avpatel** [comment]
You don't need to have separate commit for addressing review comments. Just amend your existing commit and force-push to your "hardenedlinux:master" branch.

Apart form comments already addressed, replace "BBL/OpenSBI" with "OpenSBI" in your "coreboot boot process:" diagram.

**Comment by citypw** [comment]
done, plz review!

**Comment by avpatel** [comment]
Documentation is fine now.

Can you squash your second commit into first commit and force-push again?

**Comment by avpatel** [comment]
We also have OpenSBI mailing list, you in-future you can avoid the Github PR complexity by directly sending patches to OpenSBI mailing list.

Here's the link to join OpenSBI mailing list:
http://lists.infradead.org/mailman/listinfo/opensbi

**Comment by citypw** [comment]
Done! Good to know the mailinglist can be used for patch review.

**Pull request merged**
